name: CI

on: [push]

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js v12.x
      uses: actions/setup-node@v1
      with:
        node-version: 'v12.x'
    - run: yarn --frozen-lockfile
    - run: yarn run lint
  
  deploy:
    needs: [lint]
    if: github.ref == 'refs/heads/rewrite'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js v12.x
      uses: actions/setup-node@v1
      with:
        node-version: 'v12.x'
    - run: yarn --frozen-lockfile
    - run: yarn run generate
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
